### ISSUE TITLE
How to move the image

### ISSUE THREAD

**Issue by schroef** [tizian/tonemapper#1]
I tried this app a while back and find it very nice. WHen i open an image i just see a small section and i cant move it around. Im using the last version 1.1 on osx 10.11.6

<img width="1072" alt="screen shot 2018-11-17 at 22 16 06" src="https://user-images.githubusercontent.com/6923008/48667859-786a9b00-eab6-11e8-87f7-134c464084fc.png">

However i tried it again today and noticed i could not open an HDR image saved from my render engine. It does allow me to open the exr files.

<img width="476" alt="screen shot 2018-11-17 at 22 16 00" src="https://user-images.githubusercontent.com/6923008/48667861-7f91a900-eab6-11e8-9d4a-3a331a391c2d.png">

**Comment by schroef** [comment]
Sorry just read that it only opens EXR indeed, perhaps that button should be changed. But since it was 3 years ago since last update i wonder if there is still work done on it.

**Comment by tizian** [comment]
Hi,
Thanks for posting this, and sorry for the late reply. For some reason I haven't received an automatic update about this.
I just pushed some small changes to address your comments. You can now move an opened image by dragging the mouse while holding shift. (And zoom in/out while scrolling).
Good point also about the button labels (I guess my previous reasoning was that .exr is technically a high-dynamic range image format, but it is confusing).

Indeed I haven't worked on this project in quite some time, so the changes are maybe not implemented in the most robust way. Let me know if it's working :)

Best,
Tizian

**Comment by schroef** [comment]
I used the pre-build osx version, i see that one is was not updated. I cant do the testing cause of that.

**Comment by tizian** [comment]
Ah, I assumed you'd compile the application yourself. Here is my built version for testing: https://www.dropbox.com/sh/xpzu773zoqdy5p3/AACkEzmGELK3VDihTAOkOiC7a?dl=0

**Comment by schroef** [comment]
Hmmm this works weird, not sure why we would need to press shift as a second key?

PS the zoom works weird, when i zoom in and zoom out again. The image disappears at a certain point, i can only see it again when i zoom in than. But after checking my laptop's trackpad it did work, it disappears if you scroll from my tablet (wacom).
![zoom-disappearing-image](https://user-images.githubusercontent.com/6923008/50060677-545db080-016d-11e9-98cf-1f9246931253.gif)


I also noticed the app is now locked into a low res mode, it also misses its app icon
<img width="512" alt="screen shot 2018-12-16 at 19 54 32" src="https://user-images.githubusercontent.com/6923008/50060683-693a4400-016d-11e9-80de-aee0d49613ee.png">

Old version wasnt in low res mode and icon was working.
<img width="512" alt="screen shot 2018-12-16 at 19 54 32" src="https://user-images.githubusercontent.com/6923008/50060689-7b1be700-016d-11e9-9efe-6eb00f951bd1.png">

**Comment by tizian** [comment]
> not sure why we would need to press shift as a second key?

Because I thought it  would be nicer. In 99% of the cases I don't want to accidentally move an image.

> it disappears if you scroll from my tablet (wacom). 

Well I didn't expect this to be used with a Tablet but it also behaves weirdly with a standard mouse I realized.

> I also noticed the app is now locked into a low res mode, it also misses its app icon.

Both of these things don't happen for me.

I'll investigate some and then take another stab at this as soon as I find the time.

Best,
Tizian

**Comment by tizian** [comment]
Shift is no longer necessary and scrolling should be much improved now:
https://www.dropbox.com/sh/jsp6grqaqx4wfmc/AABknMTDIWBoG4_G8yKhB78ya?dl=0

Still no idea about the icon and the "Open in low resolution"

**Comment by schroef** [comment]
Hi Tizian,

i copied the info.plist over from an older version and now the app does
show in the proper resolution. I can also toggle it now.
PS there was some old app link inside the content folder of the app so i
deleted it as well. Now the icons works as it should.

PS you need to adjust the versioning i think :)

–
Rombout

**Comment by schroef** [comment]
Hi Tizian,

i copied the info.plist over from an older version and now the app does
show in the proper resolution. I can also toggle it now.
PS there was some old app link inside the content folder of the app so i
deleted it as well. Now the icons works as it should.

PS you need to adjust the versioning i think :)

<img width="512" alt="fixed app" src="https://user-images.githubusercontent.com/6923008/50191427-3f675580-0304-11e9-956a-1d8908167a39.png">

**Comment by tizian** [comment]
Well, the versioning displayed here is also specified in the info.plist, so if you replace that of course it doesn't show the latest one.

**Comment by schroef** [comment]
Yep, didnt think of that.
