### ISSUE TITLE
Unkonwn option "--Lwhite" when using clamping operator

### ISSUE THREAD

**Issue by bigfatgreg** [tizian/tonemapper#10]
Looking at the [source](https://github.com/tizian/tonemapper/blob/b316a17c05aeb68e464a340cb42be930f0bdc2ad/src/operators/ClampingOperator.cpp#L62) for the clamping operator, it seems like `--Lwhite` should work as an argument. However, when I try to use it I am getting an error.

```
$ tonemapper --no-gui --operator clamping --Lwhite 0.01 master.hdr

Chosen operator:
    "Clamping"
    Clamps everything above a given luminance threshold to 
    1. Discussed in "Quantization Techniques for 
    Visualization of High Dynamic Range Pictures" by 
    Schlick 1994. 

Operator specific parameters:
  --gamma  Gamma correction value. 
           (Default: 2.2)



Unkonwn option "--Lwhite"
```

I'm on an M2 MacBook Air

**Comment by tizian** [comment]
Hi,
This should be fixed on the latest commit. Thanks for letting me know!

-Tizian
