### ISSUE TITLE
command mode

### ISSUE THREAD

**Issue by zcoo** [tizian/tonemapper#5]
Well, this is a very useful tool! But as a lazy user, I will be glad to use a command line to  batch process many exr files. For example "tonemapper.exe --input_path --output_name --operator "
Just a suggestion!~

**Comment by zcoo** [comment]
Another thing is that ACES method is not included in the GUI

**Comment by tizian** [comment]
I agree, having a command line argument would be a good feature to have. Unfortunately I don't have much time currently to work on this project, but I'd of course appreciate any pull request with new additions like that.

Regarding the ACES method: two versions of it are available on the `master` branch. The pre-compiled binaries are fairly outdated.

**Comment by tizian** [comment]
After a redesign of the application, version 2 now (finally) includes a command line only mode :)
