### ISSUE TITLE
Incorrect arguments used in ReinhardDevlinOperator::setParameters

### ISSUE THREAD

**Issue by Silverlan** [tizian/tonemapper#7]
I'm not sure about this one since I'm not that familiar with the algorithm, but this looks wrong to me:
`parameters["Iav_r"] = Parameter(image->getAverageIntensity().r(), "Iav_r");
parameters["Iav_g"] = Parameter(image->getAverageIntensity().r(), "Iav_g");
parameters["Iav_b"] = Parameter(image->getAverageIntensity().r(), "Iav_b");`

It uses the red-channel of the average intensity for all three parameters, I assume it should be r(), g() and b() respectively?

**Comment by tizian** [comment]
Oops -- I'm myself not familiar anymore with these but that definitely looks like a typo on my part. Nice catch!

Fixed in https://github.com/tizian/tonemapper/commit/4cb3be5126cab6abeaccf446b2970c7cbcec12b8
